export enum BillCategory {
  DEBT_PAYMENTS = 'DEBT_PAYMENTS',
  HOUSE_RENT = 'HOUSE_RENT',
  GROCERIES = 'GROCERIES',
  INTERNET_CHARGES = 'INTERNET_CHARGES',
  RETIREMENT_CHARGES = 'RETIREMENT_CHARGES',
  CELL_PHONE_CHARGES = 'CELL_PHONE_CHARGES'
}


